services:
  php-fpm:
    build:
      context: nginx/.
      dockerfile: Dockerfile-dev
    volumes:
      - .:/var/www/html
    expose:
      - "9000"

  nginx:
    image: nginx:alpine
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - php-fpm
    restart: always