name: Deploy via ftp

on:
  push:
    branches: main
  workflow_dispatch:

concurrency:
  group: build-deploy

jobs:
  deploy:
    name: Deploy to FTP
    runs-on: ubuntu-latest
    outputs:
      semVer: ${{ steps.gitversion.outputs.semVer }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v3
        with:
          versionSpec: "5.x"

      - name: Determine Version
        id: gitversion
        uses: gittools/actions/gitversion/execute@v3
        with:
          useConfigFile: true

      - name: Upload service
        uses: sebastianpopp/ftp-action@releases/v2
        with:
          host: ${{ secrets.FTP_SERVER }}
          user: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          localDir: "src"
          remoteDir: "/"
          options: "--delete"

  create_release:
    name: Create release
    needs: deploy
    env:
      SEMVER: ${{ needs.deploy.outputs.semVer }}
    runs-on: ubuntu-latest
    steps:
      - name: Create Release
        uses: ncipollo/release-action@v1.14.0
        with:
          allowUpdates: false
          skipIfReleaseExists: true
          draft: false
          makeLatest: true
          tag: v${{ env.SEMVER }}
          name: Release v${{ env.SEMVER }}
          generateReleaseNotes: true
          body: Release ${{ env.SEMVER }} of ${{ github.event.repository.name }}
